import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./component/header/page";
import Footer from "./component/footer/page";
import CartProvider from "./component/cartProvider";
import ShppingCartModel from "./component/ShppingCartModel";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>          
        <Header></Header>
        <ShppingCartModel></ShppingCartModel>
        {children}
        <Footer></Footer>
        </CartProvider>
      </body>
    </html>
  );
}